<a href="https://colab.research.google.com/github/AnshMittal1811/Pytorch/blob/master/01_PyTorch_Tensors_and_Arrays_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

In [1]:
import torch
import numpy as np

## Initializing a Tensor

This can be done using various methods. Some of them have been listed below.
1. Using a list of list
2. Using NumPy array
3. From another Tensor
4. Using random variables

In [2]:
d = [[1, 2, 3, 4], [1, 3, 4, 6]]
X_d = torch.tensor(d)

In [3]:
print(X_d)

tensor([[1, 2, 3, 4],
        [1, 3, 4, 6]])


In [4]:
print(type(X_d))

<class 'torch.Tensor'>


In [5]:
np_array = np.array(d)
x_np = torch.from_numpy(np_array)

In [6]:
print(np_array)
print(type(np_array))
print(x_np)
print(type(x_np))

[[1 2 3 4]
 [1 3 4 6]]
<class 'numpy.ndarray'>
tensor([[1, 2, 3, 4],
        [1, 3, 4, 6]])
<class 'torch.Tensor'>


In [7]:
X_ones = torch.ones_like(X_d)
print(f"One Tensor: \n {X_ones} \n")
print(f"Type: \n {type(X_ones)} \n")

X_rand = torch.rand_like(X_d, dtype = torch.float)
print(f"Random Tensor: \n {X_rand} \n")
print(f"Type: \n {type(X_rand)} \n")

One Tensor: 
 tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]]) 

Type: 
 <class 'torch.Tensor'> 

Random Tensor: 
 tensor([[0.4285, 0.7646, 0.4245, 0.7930],
        [0.6910, 0.6654, 0.4020, 0.9031]]) 

Type: 
 <class 'torch.Tensor'> 



In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Random Tensor: \n {ones_tensor} \n")
print(f"Random Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7796, 0.5266, 0.6152],
        [0.5637, 0.6480, 0.6447]]) 

Random Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Random Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Attributes of a Tensor

In [9]:
tensor = torch.rand(3,4)

print(f"Shape of a tensor: {tensor.shape}")
print(f"Datatype of a tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of a tensor: torch.Size([3, 4])
Datatype of a tensor: torch.float32
Device tensor is stored on: cpu


## Operating on Tensors

In [10]:
if torch.cuda.is_available(): 
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [11]:
tensor =  torch.ones(4,4)
print("First Row: ", tensor[0])
print("First Column: ", tensor[:, 0])
print("Last column: ", tensor[..., -1])
tensor[:, 1] = 0
print(tensor)

First Row:  tensor([1., 1., 1., 1.])
First Column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
t_1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t_1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [16]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(f"value of tensor: {tensor} \n")
print(f"value of y1: {y1} \n")
print(f"value of y2: {y2} \n")

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out = y3)
print(f"value of y3: {y3} \n")

z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(f"value of z1: {z1} \n")
print(f"value of z2: {z2} \n")

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)
print(f"value of z3: {z3} \n")

value of tensor: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

value of y1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

value of y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

value of y3: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

value of z1: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

value of z2: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

value of z3: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [17]:
agg_1 = tensor.sum()
agg_item = agg_1.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [18]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridging Torch Tensor with Numpy

In [21]:
t_1 = torch.ones(5)
print(f"t: {t_1}")
n = t_1.numpy()
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [22]:
t_1.add_(1)
print(f"t: {t_1}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## Numpy Array to Tensor

In [23]:
n_1 = np.ones(5)
t_2 =  torch.from_numpy(n_1)
np.add(n_1, 1, out = n_1)
print(f"t: {t_2}")
print(f"n: {n_1}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
